apiVersion: apps/v1
kind: Deployment
metadata:
  name: orsproject4-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orsproject4-webapp
  template:
    metadata:
      labels:
        app: orsproject4-webapp
    spec:
      containers:
      - name: orsproject4-webapp
        image: docker.io/sawanpanwar/orsproject4-webapp
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "jdbc:mysql://mysql:3306/project04"
