apiVersion: v1
kind: Service
metadata:
  name: orsproject4-webapp-service
spec:
  selector:
    app: orsproject4-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
